### PR TITLE
Sprint 4/issue 59#fix design about screen

### LINKED ISSUE #59: Fix design details on the About Screen
## REQUIREMENTS / DESCRIPTION

Details in the responsiveness of the About section

### PR DESCRIPTION
**Pull request by AlbertoG22**
# Description

What did you implemented/Why did you implemented this:

- Removed title from screen.
- Changed content layout using flex (My Specialist and My Info tabs).
- Added notch settings for ios on this screen.

## Screenshots

Texto alternativo
Texto alternativo

### CODE REVIEW

**Review by montsegv-2 — APPROVED** [review]
Amazing 🥇

**Review by mcmmiguel — APPROVED** [review]
Beautiful 🌹

**Comment by AlbertoG22** [comment]
> Beautiful 🌹

you too 😘

**Review by landillo — APPROVED** [review]
very nice!

**Pull request merged**
