### PR TITLE
Sprint 4/issue 65#fix design details on login screen

### LINKED ISSUE #65: Fix design details on the Login screen.
## DESCRIPTION
Fix design details on the Login screen.

### PR DESCRIPTION
**Pull request by AlbertoG22**
# Description

What did you implemented/Why did you implemented this:

- Changes to the color of the input text.
- Changes to the color of the slogan and the terms and conditions.
- Added horizontal padding on welcome screen.

### CODE REVIEW

**Review by mcmmiguel — APPROVED** [review]
What a great effort, good job!

**Review by AlbertoG22 — COMMENTED** [review]
LGTM
Texto alternativo

**Review by landillo — APPROVED** [review]
very nice!

**Review by montsegv-2 — APPROVED** [review]
Congratulations on a job well done ⭐

**Pull request merged**
